# Generated by Django 3.2.7 on 2021-10-01 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_transacao', models.CharField(blank=True, max_length=200)),
                ('valor_transacao', models.FloatField()),
                ('data_transacao', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo_transacao', models.CharField(max_length=200)),
            ],
        ),
    ]
