# Generated by Django 3.2.7 on 2021-10-01 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data_transacao',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
