# Generated by Django 3.2.7 on 2021-10-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_alter_transacao_data_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='valor_transacao',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
